### ISSUE TITLE
【不具合】会社概要ページの「アクセス」の駅名を変更する

### ISSUE THREAD

**Issue by na-yamaguchi** [EimeeInc/eimee-web#13]
# バグの概要

## 本来の仕様

駅名変更により船の科学館駅は東京国際クルーズターミナル駅になったため「東京国際クルーズターミナル」が現在の正しい表記。

## 現実装における挙動

現在も以前の「船の科学館」が表示されている。

# イメージ/スクリーンショット/ソースコード

![access](https://user-images.githubusercontent.com/39782963/59891220-39674400-940f-11e9-9de3-ddcd6dfffc01.png)

# 関連issue/関連資料

#7

# 修正案

以下のように文言を変更する。

- 変更前「船の科学館」
- 変更後「東京国際クルーズターミナル」

**Comment by ta-kiyama** [comment]
@na-yamaguchi さん
すぐ直せそうな内容ですし、良さそうですね。
ぱぱっとやっていきます
