### ISSUE TITLE
【変更案】アクセスの平日無料循環バスの項目を消す

### ISSUE THREAD

**Issue by yo-ando** [EimeeInc/eimee-web#17]
# 現状の仕様説明
平日無料循環バスでのアクセス方法が載っている。

# 現状仕様の課題/問題点
このバスは特定の従業員専用で当社のアクセス方法としては不適切だったことが判明。

# 提案する仕様説明
該当の項目の削除

## 提案内容におけるメリット/恩恵
不適切な項目を削除できる

## 提案内容におけるデメリット/懸念点
アクセスルートが2つになるので選択肢に乏しい印象を受けそう。

# 実装案
- 平日無料循環バスの項目を削除

**Comment by ta-kiyama** [comment]
問題ありそうな内容ですね。　#13 とセットで対応していきましょう。
