### ISSUE TITLE
【変更検討】事業内容を更新

### ISSUE THREAD

**Issue by yo-ando** [EimeeInc/eimee-web#18]
# 現状の仕様説明
- ヒカキューがクローズされたが今もWORKSや事業内容に載っている
- CHAzineがまだWORKSや事業内容に載っていない。

# 現状仕様の課題/問題点
- 事業内容が正しく載っていない状態は当社の信用にも関わる可能性がある。

# 提案する仕様説明
- ヒカキューの項目を削除しCHAzineの項目を追加する

## 提案内容におけるメリット/恩恵
- 事業内容を最新にできる。

## 提案内容におけるデメリット/懸念点
- 画像や入れる文言を作成する必要あり。

**Comment by yo-ando** [comment]
CHAzineのの画像はこちらで用意を進めていきます。

@na-yamaguchi さん
実際に入れる文言の作成をお願いしてもいいですか？

**Comment by ta-kiyama** [comment]
該当コンポーネントはここですね

https://github.com/EimeeInc/eimee-web/blob/763e0078cb4ce8c2002a098d605fef8985119509/src/components/Organism/Works.tsx

画像は `/static/assets/img/` 以下に配置しているので、ここに足していけば良さそうです

**Comment by yo-ando** [comment]
「リスティング広告代行」は実質行われていないことが判明したので、
こちらも削除した方が良さそうです。

**Comment by na-yamaguchi** [comment]
@yo-ando さん
文言作成の件、承知いたしました！

レイアウトの変更はなさそうですか？
今のデザインのままなら、CHAzineの紹介文を160～200字程度で作成しようと思います。

**Comment by ta-kiyama** [comment]
すぐ出来そうかつ重要度も高いので優先度を上げます

**Comment by yo-ando** [comment]
@na-yamaguchi さん
今大幅なデザイン変更はしないので、紹介文は挙げて貰った文字数ぐらいでお願いします。

**Comment by na-yamaguchi** [comment]
@yo-ando さん
以下の内容でお願いします。

> CHAzineは「シーンに最適なお茶が見つかる」をコンセプトにしたお茶専門のレビューブログです。仕事の合間に飲むお茶、ご飯と一緒に飲むお茶、夜寝る前に飲むお茶など、それぞれのシーンに最適なお茶を紹介しています。レビュー記事を書いているのは当社のライターです。実際に商品を試飲して、ほっと一息つきながら記事を作成しています。あなたもシーンに合ったお茶を見つけて、ほっと一息ついてみませんか？

**Comment by ta-kiyama** [comment]
@na-yamaguchi さん
ありがとうございます。
紹介文良いと思います。使っていきます💪

@yo-ando さん
画像が出来たらいつでもPR投げられますが、 @yo-ando の方でやってみますか？(そうでなければ、こちらでやります)

**Comment by yo-ando** [comment]
@ta-kiyama さん
試しにやってみたいと思います。

**Comment by yo-ando** [comment]
画像は一旦これにしようと思っています。
![ph_works_chazine](https://user-images.githubusercontent.com/39184550/59986552-4afc5600-9672-11e9-8faf-507fb09c3d03.jpg)

**Comment by ta-kiyama** [comment]
良さそうですね。
使っていきましょう。
