### ISSUE TITLE
【修正】フッター部分のエイミーロゴに入っているURLを更新

### ISSUE THREAD

**Issue by yo-ando** [EimeeInc/eimee-web#26]
# 現状の仕様説明
フッター部分のロゴに入っているURLが「http」になっている。

# 現状仕様の課題/問題点
現在のサイトのURLは「https」に更新して貰っているので画像と実際のURLにズレが出来ている。

# 提案する仕様説明
画像を更新する。

## 提案内容におけるメリット/恩恵
正しい情報が載せられる。

## 提案内容におけるデメリット/懸念点
特になし。

# イメージ/スクリーンショット/ソースコード
ここ
![image](https://user-images.githubusercontent.com/39184550/59914041-79044f00-9454-11e9-8293-93002d1abce1.png)

**Comment by ka-yamano** [comment]
httpのままでアクセスしても301 Moved Permanentlyになってhttpsのほうにリダイレクトされるため、対応する必要はなさそうに見えます:eyes:
