### ISSUE TITLE
【不具合】Google Analytics のデータが計測されていない

### ISSUE THREAD

**Issue by ma-yoshimoto** [EimeeInc/eimee-web#29]
# バグの概要
先日のEimee-Webサイト移管の後から、Google Analyticsでの計測がされなくなっている。

## 本来の仕様

ユーザーのアクセスデータが計測されること。

## 現実装における挙動

 6/20以降、データが計測されていない。

# イメージ/スクリーンショット/ソースコード

![image](https://user-images.githubusercontent.com/36143372/60225726-f6034e80-98c2-11e9-8465-19afa98af01b.png)

# 修正案

サーバー移管したこと、https化したことにより、Google Analytics側で再設定が必要かもしれない。

## 修正案におけるメリット/恩恵

アクセスユーザーの行動分析ができる。

## 修正案におけるデメリット/懸念点

 特になし。

**Comment by ta-kiyama** [comment]
@ma-yoshimoto さん
主要開発メンバー側で何か出来ることはありますか？

**Comment by ma-yoshimoto** [comment]
@ta-kiyama さん
Google Analyticsは社員皆が設定確認できる権限を与えているので、メンバー側で一度確認してみてほしいです。
つい先日CHAzineでの設定を @ko-murakami さんが対応しているので、その辺りの確認や設定対応のお願いすることの相談をしてみても良いかと思います。

**Comment by ta-kiyama** [comment]
調査の結果、リニューアル後にscriptタグを貼り忘れていた事がわかりました。
単純にクライアントサイドにスクリプトを貼ることで解決できそうです。

一方で、アナリティクスで埋め込み指定するUAの情報は汎化させておきたいので、この部分のみ環境変数で渡すようにし、ビルド時に埋め込むようにしようと思います。

**Comment by ta-kiyama** [comment]
旧ページで使われていたスクリプトがanalytics.jsであるため、ここも改修して現行のGoogle Analyticsが推奨しているgtag.jsに移行します

**Comment by ta-kiyama** [comment]
#30 で対応した。
数日様子を見て、問題なさそうであれば閉じる

**Comment by ta-kiyama** [comment]
正常に動作することを確認したので閉じる
