### ISSUE TITLE
【提案】デプロイ方法を考える

### ISSUE THREAD

**Issue by ta-kiyama** [EimeeInc/eimee-web#5]
# 背景

実装がほとんど完成し、いつでも公開できる状態になった。
一方で、デプロイ方法等はまだ検討しておらず、方法について考える必要がある

# 機能の概要

デプロイ方法を決定する

## 提案機能におけるメリット/恩恵

- 新Webページを公開できる

## 提案機能におけるデメリット/懸念点

なし

# 解決案

- AWSとGitHub Pagesを併用する
  1. GitHub上でプロジェクトをpublicリポジトリ化する
  1. GitHub Pagesにstaging環境をリリース
  1. AWS上にアップロード

## 解決案におけるメリット/恩恵

- 今まで存在してなかったstaging環境を作成できる
  - 外部に公開することでissueやPRを外部から求めることが出来る
- 現行のproductionビルド環境の一部を流用できる

## 解決案におけるデメリット/懸念点

- AWSである必要性が薄い
  - 無料の静的ホスティングサービスはたくさん存在する
    - GitHub Pages, Heroku, now, Netlify, etc...
- staging環境でnoindex/nofollow指定が必要になる
  - いっその事GitHubPagesをstaging/production併用でも問題なさそうな開発規模ではある

**Comment by ta-kiyama** [comment]
私自身の理解による比較をします。
(最新ではない情報や、あやふやなところも若干含みます。)

## 候補1: AWS上へのデプロイ

### メリット

- 既存のデプロイシステムを流用できる
- 安定した企業＆お金を払っているという安心感がある(？)

### デメリット

- 他の2つの手法とは異なり有料
- デプロイシステムを組むのが(ちょっとどころではなく)面倒

## 候補2: Netlifyへのデプロイ

### メリット

- GitHub連携が楽
  - masterブランチを監視してビルドコマンドとpublishディレクトリの指定などが可能なのでとにかく楽
  - https://diwao.com/2018/03/netlify-ssl.html
- リダイレクト設定が楽
  - 今まで `/path/to.html` のように拡張子をつけてしまうルーティングで見せてしまっていたが、これを `/path/to/` への301リダイレクトにするなどの指定も簡単

### デメリット

- 既存のcloudfront&S3構成からの脱却が必要

## GitHub Pagesへのデプロイ

### メリット

- GitHubサービスだけでほぼ完結するので楽

### デメリット

- SSL化が若干面倒
  - 通常はCloudFrareなどの外部DNS(CDN)サーバーを利用する必要がある
- (CloudFrare側の制約で)リダイレクト等のルール設定個数上限に制限がある(無料アカウント限定)
- **Netlifyと比較して優位性がほぼない**

**Comment by ma-yoshimoto** [comment]
@ta-kiyama さん
他ホスティングサービスとの比較検討ありがとうございます。

> ## 候補1: AWS上へのデプロイ
> ### メリット
> * 既存のデプロイシステムを一部流用できる
> * 安定した企業＆お金を払っているという安心感がある(？)
> * 無料でAWSのSSL/TLS証明書を発行してもらえる

安定がAWSの一番の利点と思ってます。
可用性99.9999...%といっているので、ほぼ稼働停止することがないであろうと思っています。
（急激なアクセス負荷増も、AWS側お任せで安心なはず）
ちなみにEimee-Webはまだhttps化しておらず、AWSでSSL発行するとCloudFrontは必須になるので、そのCloudFront利用料が少し（1～2 ドル/月？）上乗せされるかもしれません。
> ### デメリット
> * 他の2つの手法とは異なり有料
> * デプロイシステムを組むのが(ちょっとどころではなく)面倒

有料なのは他と比べるとデメリットになりますが、S3、Route53の利用料で約2～3 ドル/月 くらいなので、それくらいなら可用性を取りたいです。

> ## 候補2: Netlifyへのデプロイ
> ### メリット
> * GitHub連携が楽

GitHub連携のしやすさとコスト（無料）面からみると、これが @ta-kiyama さんのイチオシですか？


> ## 候補3: GitHub Pagesへのデプロイ
> ### メリット
> * GitHubサービスだけでほぼ完結するので楽
> 
> ### デメリット
> * 比較的サーバーが落ちやすい

リクエスト数の制限はなくなった？ようですが、サーバーが落ちやすいのは避けたいですね…

https://qiita.com/tonishi/items/e5696b477278f3c49b77


優先順位としては

1. 安定稼働
2. 料金
3. デプロイしやすさ

と考えていて、挙げてもらった３つの内容からだと、個人的にはAWSでの運用がいいかなと思います。

**Comment by ta-kiyama** [comment]
@ma-yoshimoto さん
> 安定がAWSの一番の利点と思ってます。
> 可用性99.9999...%といっているので、ほぼ稼働停止することがないであろうと思っています。

なるほどです。それはCDN全般に対して言える性質なので、AWSがどうとかいう話はあまり議論には出来ないと思います。

例えばGitHubPagesでは、GitHubPages単体での利用では記事の通り10万リクエストが上限なので正しいですが、通常はSSL化対応等のためにCDN(CloudFront等)を併用するケースが多いため、(キャッシュがCDN上に置かれさえすれば)可用性という論点では全ての環境が同程度です。

料金についてはむしろAWSがデメリットのように感じられますが、どういう理由ですか？

> GitHub連携のしやすさとコスト（無料）面からみると、これが @ta-kiyama さんのイチオシですか？

私のイチオシはこれですね。

**Comment by ta-kiyama** [comment]
スパイク対応時のコスト計算をしてみました。

前提: Gatsby版eimee-webのトップページは `3.8MB/request`

特定のスパイクで(ブラウザキャッシュの効かない)ユニークユーザーの10万リクエストが来た時を仮定します。

この時、総帯域は `3.8MB * 100000req = 371GB` です。

Netlifyは、無料枠100GBに加えて、100GB毎に$20の追課金が必要になります。
371GBの帯域のときには、$60が必要になります。

ここで、AWSで通常利用する場合が `$3/month` と仮定すると、20ヶ月分の金額に相当します。

ですので、2年半に1度スパイクが発生するという頻度の時に、NetlifyとAWSで金額が同程度になると考えることが出来ます。

(※実際はAWS側でもスパイクが発生した時に課金額が増えるので、2年半よりも短い計算になります。)

そして、2年半に1度という頻度は考えにくいと言っても過言ではないでしょう。
(そんなに頻繁に起きてしまうと、企業としての信頼があるかが懐疑的です。)

----

以上をまとめると、スパイクが発生した際についても、AWSとNetlifyでは、Netlifyの方が高い確率で低コストで抑えられることがわかります。

**Comment by ma-yoshimoto** [comment]
@ta-kiyama さん
なるほど、全ての候補ともCDNを経由すため、可用性同程度というのは納得です。
今後コンテンツを増やしていくと変わってくるかもしれませんが、現時点ではそこまでの高負荷・アクセスは想定されないとは思うので、無料でかつGitHub連携もしやすいのであれば、Netlifyの方がよさそうですね。

ということでNetlifyで進めてもらって良いかと思うのですが、デメリットの一つ

>Let's Encrypt証明書で満足できないという場合には別途有料証明書を発行する必要がある

で「満足できない」というのは、信頼性が低い？とある危険性がある？ということでしょうか。

**Comment by ta-kiyama** [comment]
@ma-yoshimoto さん
> で「満足できない」というのは、信頼性が低い？とある危険性がある？ということでしょうか。

Let's Encryptの利用している認証局も有料の証明書の認証局も、認証局なので信頼性や危険性は同程度です。

単に気持ちの問題で、「証明書の開示をした時に、Let's Encryptと表示するのが気に入らない(劣等感を感じる)」という心理的障害を感じるかどうかの違いです。
(ドメインバリューとかと同じ認識でいたら良いと思います。)

**Comment by ta-kiyama** [comment]
もっと分かりやすく言うと、宗教です。

**Comment by ma-yoshimoto** [comment]
@ta-kiyama さん
そんな宗教には入信してないので、Let's Encryptで問題はないと考えます 👍 
Netlify 利用の方向で進めて下さい。

**Comment by ta-kiyama** [comment]
やっていきます
アカウント作成周りだけお願いしたいのですが、良いですか？

**Comment by ma-yoshimoto** [comment]
了解です。
アカウント作成出来たらお知らせします。

**Comment by ma-yoshimoto** [comment]
@ta-kiyama さん
アカウント作成し、shared上でNetlifyにログインした状態にしておきました。
EimeeIncの各リポジトリは参照できる状態になっていますので、各種設定をお願いできればと思いますが、Netlifyへの移行計画、どのような作業手順を想定しているか、確認させてもらえますか？

個人的に主に気になっている点は、eimee.co.jpドメイン、DNS周りについてですが、そこは現状のAWS Route53を引き続き利用するのか、Netlify側に全て移行できる？（した方が良い？）のかというところです。

**Comment by ta-kiyama** [comment]
> 個人的に主に気になっている点は、eimee.co.jpドメイン、DNS周りについてですが、そこは現状のAWS Route53を引き続き利用するのか、Netlify側に全て移行できる？（した方が良い？）のかというところです。

その辺りのことは全部Netlify側でできます。
具体的には、独自ドメインの指定とビルドタスクの設定とオートスケーリングとルーティングはNetlify側でサポートしています。

**Comment by ma-yoshimoto** [comment]
なるほど。
そこまで出来て無料なのか…
であれば全て移行ですね。

その辺りも含めて、移行に伴う全作業は @ta-kiyama さんにお願いできればと考えていますが、  @ma-yoshimoto  の方でやってほしい作業や、事前に知っておきたい情報、懸念点等あれば教えてください。

**Comment by ta-kiyama** [comment]
移管出来ました👏
