### ISSUE TITLE
【提案】コンソール上にGitHubリポジトリへの誘導を表示させたい

### ISSUE THREAD

**Issue by ta-kiyama** [EimeeInc/eimee-web#8]
# 背景

EimeeInc/eimee-webは昨日public repositoryになった。
このリポジトリの存在は広く周知されておらず、エイミーに興味のあるコアターゲットにこのリポジトリを伝える必要が出てきた。

# 機能の概要

eimee-webのコンソール上に、このGitHubリポジトリへのリンクを表示させる

## 提案機能におけるメリット/恩恵

- コアターゲットに対して効果的に存在を伝えることが可能
  - その企業に興味のあるエンジニアは、その企業のWebページのソースコードを読む傾向にあるため

## 提案機能におけるデメリット/懸念点

- コアターゲット以外に対しての宣伝効果は薄い
  - やり得な機能ではあるので、とりあえず実装するのは手だと思われる

# 解決案

`console.info` に色々装飾してURLを貼り付ける

## 解決案におけるメリット/恩恵

- `console.log` と違い意図的に行っているログであることが伝わるため、より効果が期待できる

## 解決案におけるデメリット/懸念点

- 文面を何も考えていないので、考えていく必要がありそう

**Comment by ka-yamano** [comment]
企業ページのコンソールを開くと出てくるアレですね！
少し作るのが大変そうですが、eimeeのロゴのアスキーアート + URLを出すのが良いと思います。

**Comment by ta-kiyama** [comment]
https://qiita.com/koinori/items/83f119cb2d82c0ca2c1e#%E7%95%AA%E5%A4%96%E7%B7%A8ascii%E3%82%A2%E3%83%BC%E3%83%88

でAAを作れそう

**Comment by ma-yoshimoto** [comment]
昔スーモで見たなというのを思い出しました。
（スマホ版ページしか出ないようです）

https://suumo.jp/sp/

**Comment by ta-kiyama** [comment]
chromeだとstyle指定ができるのでよりリッチに出来ますね👏

**Comment by ka-yamano** [comment]
`image-to-ascii`を試してみましたが、`\u001b[38;5;231m@`のようなANSIスタイルの色付きテキストをChromeが解釈できないので、普通に力技でstyleをあてて作ったほうが綺麗なものが出来上がりそうな感じはします。

これはあくまで参考ですが、色なしAAだとこんなものが出力されています。

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@888888@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@8GGCCCCCCGG08@@@@@@@@@@@8888888888@@@@@@8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@8GCCCCCCCCCCCCG0@@@@@@@@@1:::::::::;G@@@C;:L@@@@GLL0Lt1tL00Ct11fG@@@@@@0CffLG8@@@@@@8GLffLG8@@@@
@@@0CCCCCCCCCCCCCCCCG@@@@@@@@; ,tfffffff0@@@G1iC@@@0, ,tLfi  :tff1. ,0@@@C;,,;;:.:f8@@8f:.:;;,.;C@@@
@@@GCCCCCCCCCCCCLLLCC8@@@@@@@; ,tfffffL@@@@@01;C@@@0. i@@@8: ,0@@@i .G@@C..tGGL1. .f@@t ,L0Cf;  ,G@@
@@8CCCCCCCCCCCCLffffL0@@@@@@@; .;;;;;;18@@@@C  L@@@0. i@@@8: :8@@@1 .G@@1 ,i:,,;1LG8@8: :i:,:itL08@@
@@@GCCCCCLCCCLLfffffL8@@@@@@@; :G0000000@@@@C  L@@@0. i@@@8: :8@@@1 .G@@G,  iLGGf;10@@L. .1CGG1;f8@@
@@@8GCCCLffLfffffffL0@@@@@@@@; .,,,,,,,,G@@@C. L@@@0, 1@@@8; :8@@@1 .G@@@G1:,::,,;L@@@@Ci,,:,,:1G@@@
@@@@@8GCLfffffffLLG8@@@@@@@@@GCCCCCCCCCC8@@@8CC0@@@8CC0@@@@GCG@@@@0CC8@@@@@8GCCG0@@@@@@@@8GCC08@@@@@
@@@@@@@80GCCCCG088@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by ta-kiyama** [comment]
コンバーター、ありました
https://www.npmjs.com/package/anser

**Comment by ta-kiyama** [comment]
やや話を広すぎた感がありますので、スモールスタートとしては以下の情報のみを簡素に表示する実装からやっていきたいと思います。

- このリポジトリへのURL

その後機能拡張のissue/PRは継続して募集をかけます

**Comment by ka-yamano** [comment]
`image-to-ascii`の変換結果をそのままAnserに流し込むと`"fg": "undefined, undefined, undefined"`になってしまうことがあり、一筋縄ではいかないようです:thinking:

**Comment by ta-kiyama** [comment]
仮実装がmergeされましたが、引き続き help wanted でissueを続けます

**Comment by ka-yamano** [comment]
asciify-imageで変換したものをAnserに流し込んでスタイルを当てたらできました。

![eimee](https://user-images.githubusercontent.com/48110429/60164893-58b00800-9839-11e9-8d73-2a245df7695e.jpg)

アイコンくらいなら背景色をつけても変にならないかもしれません。
個人的には文字で構成されていたほうが好みですが、今のままだと少しeimeeの文字が見づらい気がしています。

![eimee2](https://user-images.githubusercontent.com/48110429/60166634-7f237280-983c-11e9-946a-da9350c85954.jpg)
